service_club_tmp.event_class_section.*:
  type: config_entity
  label: 'Event class section config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    weight:
      type: integer
      label: 'Weight'
    heading:
      type: string
      label: 'Heading'
    description:
      type: text
      label: 'Description'
